pipeline {
    agent any
   
    
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: 'master' ]],
                         userRemoteConfigs: [[url: 'https://github.com/sagarkolhe777/sample-maven-app.git']]])
            }
        }     
        stage('Build') {
            steps {
                echo "Build Phase"
            }
        }
        stage('Test') {
            steps {
                echo "Test Phase"
            }
        }
        stage('Deliver') {
            steps {
                echo "Delivery Phase"
            }
        }
    }
}
