pipeline {
    agent any
   
    
    stages {
        stage('Checkout Project') {
          steps {
              git branch: 'master',
                  url: 'ssh://git@github.com:sagarkolhe777/sample-maven-app.git'

              sh "ls -lat"
            }
        }
        stage('Build') {
            steps {
                echo "Build Phase"
            }
        }
        stage('Test') {
            steps {
                echo "Test Phase"
            }
        }
        stage('Deliver') {
            steps {
                echo "Delivery Phase"
            }
        }
    }
}
