pipeline {
    agent any
    
    environment {
        BRANCH_NAME = 'master'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: "${BRANCH_NAME}" ]],
                         userRemoteConfigs: [[credentialsId: 'git-hub-credentials', url: 'https://github.com/sagarkolhe777/sample-maven-app.git']]])
                echo "Checkout Done"
            }
        }    
        stage('Compile') {
            steps {
               bat 'mvn clean compile'
               echo 'Comile Done'
            }
        }
        stage("SonarQube Analysis") {
            steps {
              withSonarQubeEnv('SonarQube') {
                bat 'mvn clean package sonar:sonar'
                echo 'SonarQube Analysis Done'  
              }
            }
        }
        stage("Quality Gate") {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
        }
        stage('Test') {
            steps {
               bat 'mvn test'
               echo 'Test Done'
            }
        }
        stage('Build') {
            steps {
               bat 'mvn clean install'
               echo 'Build Done'
            }
        }
    }
}
